Blog/urls.py
from email.mime import image
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path("members/",include('members.urls'))
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

 

members/urls.py
from django.urls import path
from .views import (
    user_register,
    user_login,
    user_logout,
    UserEditView,
    PasswordChangeView,
    ShowProfilePageView,
    EditProfilePageView,
    CreateProfilePageView
  
)



app_name = "members"
urlpatterns = [
   path('register/',user_register,name='register'),
   path('login/',user_login,name='login'),
   path('logout/',user_logout, name="logout"),
   path('edit_profile/',UserEditView.as_view(), name="edit_profile"),
   path('password/',PasswordChangeView.as_view(template_name=  'members/change_password.html'),name ='password'),
   path('<int:pk>/profile',ShowProfilePageView.as_view(),name = 'show_profile'),
   path('<int:pk>/edit_profile_page',EditProfilePageView.as_view(),name='edit_profile_page'),
   path('create_profile_page/',CreateProfilePageView.as_view(),name = 'create_profile_page'),
  
]

posts/urls.py
from unicodedata import name
from django.urls import path

from posts.models import Category
from .views import (
   DeletePostView,
   HomeView,
   DetailsVeiw,
   AddPostView,
   UpdatePostView,
   DeletePostView,
   AddCategoryView,
   categoryview,
   # likeView,
   AddCommentView
   
)


app_name = "posts"
urlpatterns = [
   path('',HomeView.as_view(), name='home'),
   path('details/<int:pk>',DetailsVeiw.as_view(), name = 'details'),
   path('add_post/',AddPostView.as_view(),name="add_post"),
   path('add_category/',AddCategoryView.as_view(),name="add_category"),
   path('edit/<int:pk>',UpdatePostView.as_view(), name='edit_post'),
   path('delete/<int:pk>',DeletePostView.as_view(), name='delete_post'),
   path('category/<str:category>',categoryview,name="category"),
   # path('like_post/<int:pk>',likeView,name="like_post"),
   path('details/<int:pk>/add_comment',AddCommentView.as_view(),name="add_comment"),
   
]

posts/models.py
from calendar import c
from distutils.command.upload import upload
from email.mime import image
import imp
from pyexpat import model
from turtle import title
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return reverse("posts:details", args=(str(self.id)))
        return reverse("posts:home")
class Profile(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE )
    bio = models.TextField()
    profile_image = models.ImageField(blank = True, null = True, upload_to = 'profile/')
    website_url = models.CharField(max_length=255,blank = True, null = True)
    facebook_url = models.CharField(max_length=255,blank = True, null = True)
    twitter_url= models.CharField(max_length=255,blank = True, null = True)
    instagram_url = models.CharField(max_length=255,blank = True, null = True)
    linkedin_url = models.CharField(max_length=255,blank = True, null = True)
    # def __str__(self):
    #     return str(self.user)

    def get_absolute_url(self):
        return reverse("posts:home")
class Post(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(blank = True, null = True, upload_to = 'media/')
    title_tag = models.CharField(max_length=255)
    author = models.ForeignKey(User,on_delete=models.CASCADE) # ForeignKey means OneToMany
    # description = models.TextField()  
    description = RichTextField(blank = True,null =True)
    post_date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=255,default='django')
    snippet = models.CharField(max_length=255)
    likes = models.ManyToManyField(User,related_name='blog_posts')
    # def __str__(self):
    #     return str(self.id) + " | " + self.title + " | " + str(self.author)

    def get_absolute_url(self):
        # return reverse("posts:details", args=(str(self.id)))
        return reverse("posts:home")
    

class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    

    # def __str__(self):
    #     return '%s- %s' % (self.post.title,self.name)

posts/forms.py
from dataclasses import fields
from pyexpat import model
from random import choice
from tkinter import Widget
from django import forms
from .models import Comment, Post,Category

# cats = [
#     ('coding','coding'),
#     ('sports','sports'),
#     ('Math','Math'),
# ]
cats = Category.objects.all().values_list('name','name')

choice_list = []

for item in cats:
    choice_list.append(item)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','title_tag','author','category','description','snippet','image')
        
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}),
            'title_tag':forms.TextInput(attrs={'class':'form-control'}),
            'author':forms.TextInput(attrs={'class':'form-control', 'value':'','id':'userid','type':'hidden'}),
            # 'author':forms.Select(attrs={'class':'form-control'}),
            'category':forms.Select(choices=choice_list,attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control'}),
            'snippet':forms.Textarea(attrs={'class':'form-control'}),
            

        }


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','title_tag','description','snippet')
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}),
            'title_tag':forms.TextInput(attrs={'class':'form-control'}),
            # 'author':forms.Select(attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control'}),
            'snippet':forms.Textarea(attrs={'class':'form-control'}),
        }



# Create form for Comments 
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','description')
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control'}),  
        }

posts/views.py
from ast import arg
from audioop import reverse
from dataclasses import fields
from gc import get_objects
from importlib.resources import path
from operator import mod
from pyexpat import model
from re import template
from statistics import mode
from types import CellType
from unittest import mock
from django.shortcuts import render,redirect,get_object_or_404
from django.template import context
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Category, Post,Comment

# from posts.models import Post
from .forms import PostForm,UpdateForm,CommentForm
# Create your views here.

# likes
# def likeView(request,pk):
    # post = get_object_or_404(Post,id = request.POST.get('post_id'))
    # post = get_objects(Post,id = request.POST.get('post_id'))
    # post.likes.add(request.user)
    # return HttpResponseRedirect(reverse('posts:details',args = [str(pk)]))
    # return redirect(reverse('posts:details',args = [(pk)]))
    # return redirect('posts/details.html',args = [(pk)])
    # return redirect('posts:details')



    
class HomeView(ListView):
    model = Post
    template_name = 'posts/home.html'
    ordering = ['-post_date']
    # for category
    def get_context_data(self,*args ,**kwargs):
        category_menu = Category.objects.all()
        context = super(HomeView,self).get_context_data(*args,**kwargs)
        context['category_menu'] = category_menu
        return context


    

class DetailsVeiw(DetailView):
    model = Post
    template_name = 'posts/details.html'
    def get_context_data(self,*args ,**kwargs):
        category_menu = Category.objects.all()
        context = super(DetailsVeiw,self).get_context_data(*args,**kwargs)
        context['category_menu'] = category_menu
        return context


class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = "posts/add_post.html"
    # fields = "__all__"
    # we cannot use the fields and form_class in the same class

    def get_context_data(self,*args ,**kwargs):
        category_menu = Category.objects.all()
        context = super(AddPostView,self).get_context_data(*args,**kwargs)
        context['category_menu'] = category_menu
        return context

class AddCategoryView(CreateView):
    model = Category
    # form_class = PostForm
    template_name = "posts/add_category.html"
    fields = "__all__"
    def get_context_data(self,*args ,**kwargs):
        category_menu = Category.objects.all()
        context = super(AddCategoryView,self).get_context_data(*args,**kwargs)
        context['category_menu'] = category_menu
        return context
    


class UpdatePostView(UpdateView):
    model = Post
    form_class = UpdateForm
    template_name = 'posts/update_post.html'
    def get_context_data(self,*args ,**kwargs):
        category_menu = Category.objects.all()
        context = super(UpdatePostView,self).get_context_data(*args,**kwargs)
        context['category_menu'] = category_menu
        return context
    

class DeletePostView(DeleteView):
    model = Post
    template_name = "posts/delete.html"
    success_url = reverse_lazy('posts:home')
    def get_context_data(self,*args ,**kwargs):
        category_menu = Category.objects.all()
        context = super(DeletePostView,self).get_context_data(*args,**kwargs)
        context['category_menu'] = category_menu
        return context



def categoryview(request,category):
    category_post = Post.objects.filter(category = category.replace('-',' '))
    context = {
        'category':category.title().replace('-',' '),
        'category_post':category_post
    }
    return render(request,'posts/category.html',context)

# def categorylistview(request):
#     cats_list = Category.objects.all()
#     context = {
       
#         'cats_list':cats_list
#     }
#     return render(request,'posts/category_list.html',context)



# "Adding Comment Section"

class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = "posts/add_comment.html"
    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('posts:home')
    
    

templates/posts/add_category.html
{% extends '../base.html' %}
{% block title %}Add Category{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
<h1 class="text-center my-5">Add Category</h1>
<div class="container my-5 border">
    <br><br>
 <div class="form-group">

     <form action="" method="POST">
         {% csrf_token %}
         {{form.as_p}}
         <button class="btn btn-success">Add Category</button>
        </form>
        
    </div>
    {% else %}
    <h1 class="text-center my-5">You are not allowed here!</h1>
    {% endif %}
</div>
{% endblock content %}

templates/posts/add_comment.html
{% extends '../base.html' %}
{% block title %}Comment On Blog Post{% endblock title %}

{% block content %}

<h1 class="text-center my-5">Add Comment</h1>
<div class="container my-5 border">
    
 <div class="form-group">
     <form action="" method="POST" >
         {% csrf_token %}
         {{form.as_p}}
         <button class="btn btn-success">Add Comment</button>
        </form>
    </div>
    
</div>
{% endblock content %}

templates/posts/add_post.html
{% extends '../base.html' %}
{% block title %}Add Post{% endblock title %}

{% block content %}

<h1 class="text-center my-5">Add Post</h1>
{% if user.is_authenticated %}
<div class="container my-5 border">
    <br><br>
 <div class="form-group">
     <form action="" method="POST" enctype="multipart/form-data">
         {% csrf_token %}
         {{form.media}}
         {{form.as_p}}
         <button class="btn btn-success">Save</button>
        </form>
    </div>
    <script>
        var id = "{{ user.id }}" 
        document.getElementById('userid').value = id
    </script>
</div>
{% else %}
<h1 class="text-center my-5">You are not allowed here!</h1>
{% endif %}
{% endblock content %}

templates/posts/category.html
{% extends '../base.html' %}
{% block title %}Category{% endblock title %}
{% block content %}
{% if user.is_authenticated %} 
<h1 class="text-center my-5">{{category}}</h1>
<ul>
    
    <div class="container my-5">
        {% for post in category_post %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <small>
                    
                    <div><span class="fw-bold"><b><a href="{% url 'posts:details' post.pk %}">{{post.title}}</b></a></span> -
                        {{post.post_date}} - 
                        {{post.author.first_name}} - {{post.author.last_name}} - 
                        {% if user.is_authenticated %}
                        <a href="{% url 'posts:edit_post' post.pk %}">Edit</a> -
                        <a href="{% url 'posts:delete_post' post.pk %}">Delete</a>
                        {%endif%}
                    </div>
                </small>
                
                <p>{{post.description|truncatewords:30 | safe}}</p>
                <div class="mt20">
                    <a href="{% url 'posts:details' post.pk %}" class="btn btn-lght">Read More</a>
                </div>
            </div>
            
        </li>
        
        
        {%endfor%}
    </div>
    
</ul>
{% else %}
<h1 class="text-center my-5">Sorry! This page is not exist...</h1>
{% endif %} 
{% endblock %}

templates/posts/category_list.html
{% extends '../base.html' %}
{% block title %}Blog Categories{% endblock title %}
{% block content %}
<h1>Blog Categories</h1>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
  <h4>  
      <a class="dropdown-item" href="{% url 'posts:category' item|slugify %}">{{item}}</a>
    </h4>  {% for item in cats_list %}
      {% endfor %}
     
  </div>
{% endblock %}

templates/posts/delete.html
{% extends '../base.html' %}
{% block title %}Delete Post{% endblock title %}

{% block content %}
{% if user.id == post.author.id%}
<h1 class="text-center my-5">Delete Post</h1>
<div class="container my-5">
    <br><br>
    <div class="form-group">
        <h3>{{post.title}}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <br>
            <strong>Are you sure?</strong>
            <br><br>
            <button class="btn btn-Danger ">Delete Post!</button>
        </form>
        
    </div>
    {% else %}
    <h1 class="text-center my-5">You are not the correct user to delete this post</h1>
    {% endif %}
</div>
{% endblock content %}

templates/posts/details.html
{% extends '../base.html' %}
{% block title %}{{post.title_tag}}{% endblock title %}
{% block content %}
{% load static %}
<div class="container my-5">
  <h1>{{post.title}}</h1>
  <small>By: {{post.author.first_name}}
    {{post.author.last_name}} -
    {{post.post_date}} -
    {% if user.is_authenticated %}
    {% if user.id == post.author.id%}
    <a href="{% url 'posts:edit_post' post.pk %}">Edit</a> -
    <a href="{% url 'posts:delete_post' post.pk %}">Delete</a>
    {% endif %}
    {% endif %}


  </small>
  <hr>
  <br>
  {% if post.image %}
  <img src="{{post.image.url}}" alt="">
  <!-- <img src="/media/{{post.image}}" alt=""> -->
  {% endif %}
  <br>
  {{post.description | safe}}
  <br>
  <a href="{% url 'posts:home' %}" class='btn btn-light my-5'>Back</a>
  <hr>
  {% comment %} <form action="{% url 'posts:like_post' post.pk%}" method='POST'>
    {% csrf_token %}
    <button type="submit" name='post_id' value="{{post.id}}" class="btn btn-primary btn-sm">Like</button>
  </form> {% endcomment %}
  <br>

  <div class="card mb-3" >
    <div class="row g-0">
      <div class="col-md-2">
        {% if profile.profile_image %}
        <!-- {% if post.author.profile.profile_image %} -->
        <span >
          <img src="{{post.author.profile.profile_image.url}}" class="img-fluid"
       alt="..."></span>
       {% else %}
       <span class="profile-image card-img">
        <img src="{% static 'img/defualt-img.png' %}"
     alt="..."></span>
       {% endif %}  
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <h5 class="card-title text-center">
            {{post.author.first_name}}
            {{post.author.last_name}}
          </h5>
          <p class="small text-muted text-center">
            
            <a href="{% url 'members:show_profile' post.author.profile.id %}">Profile Page</a> |
            {% if post.author.profile.website_url%}
            <a href="{{post.author.profile.website_url}}">Website</a> |
            {% endif %}
            {% if post.author.profile.facebook_url%}
            <a href="{{post.author.profile.facebook_url}}">Facebook</a> |
            {% endif %}
            {% if post.author.profile.twitter_url%}
            <a href="{{post.author.profile.twitter_url}}">Twitter</a> |
            {% endif %}
            {% if post.author.profile.instagram_url%}
            <a href="{{post.author.profile.instagram_url}}">Instagram</a> |
            {% endif %}
            {% if post.author.profile.linkedin_url%}
            <a href="{{post.author.profile.linkedin_url}}">LinkedIn</a>
            {% endif %}
          </p>
          <p class="card-text text-center">{{post.author.profile.bio}}</p>
        </div>
      </div>
    </div>
  </div>
  <!-- <img src="/profile/{{post.profile_image}}" alt=""> -->


  <h1>Comments</h1>
  <br>
  <!-- The Post and comments are connected through the foriegn key -->
  {% if not post.comments.all %}
  No Comments Yet <a href="{% url 'posts:add_comment' post.pk%}">Add One</a>
  {% else %}
  <a href="{% url 'posts:add_comment' post.pk%}">Add Comment</a>
  {% for comment in post.comments.all  %}
  <strong>  
  <br>
  {{comment.name}} -
  {{comment.date_added}}
</strong>
<br>
{{comment.description}}
<br>
  {% endfor %}
  <a href="{% url 'posts:add_comment' post.pk%}">Add Comment</a>
  {% endif %}
  <br><br>
  


</div>
{% endblock %}

templates/posts/home.html
{% extends '../base.html' %}
{% block title %}Home{% endblock title %}Home
{% block content %}
<div class="container my-5">

  <ul class="list-group ">
    {% for post in object_list %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <small>

          <div><span class="fw-bold"><b><a href="{% url 'posts:details' post.pk %}">{{post.title}}</b></a></span> -
            <a href="{% url 'posts:category' post.category|slugify %}">{{post.category}}</a> - 
            {{post.post_date}} - 
            {{post.author.first_name}} - {{post.author.last_name}} - 
            {% if user.is_authenticated %}
            {% if user.id == post.author.id%}
            <a href="{% url 'posts:edit_post' post.pk %}">Edit</a> -
            <a href="{% url 'posts:delete_post' post.pk %}">Delete</a>

            {%endif%}
            {%endif%}
          </div>
        </small>
        {{post.snippet}}
        {% comment %} <p>{{post.description|truncatewords:30 | safe}}</p> {% endcomment %}
        <div class="mt20">
          <a href="{% url 'posts:details' post.pk %}" class="btn btn-lght">Read More</a>
        </div>
      </div>
      <!-- <span class="badge bg-primary rounded-pill">14</span> -->
    </li>

    {% endfor %}
  </ul>

</div>

{% endblock %}

templates/posts/update_post.html
{% extends '../base.html' %}
{% block title %}Edit Post{% endblock title %}

{% block content %}

{% if user.id == post.author.id%}
<h1 class="text-center my-5">Update Post</h1>
<div class="container my-5 border">
    <br><br>
    <div class="form-group">
        
        <form action="" method="POST">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <button class="btn btn-success">Update</button>
        </form>
        
    </div>
</div>
{% else %}
<h1 class="text-center my-5">You'r not the correct user to update this post</h1>
{% endif %}
{% endblock content %}