Blog/urls.py
from email.mime import image
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path("members/",include('members.urls'))
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

 

members/urls.py
from django.urls import path
from .views import (
    user_register,
    user_login,
    user_logout,
    UserEditView,
    PasswordChangeView,
    ShowProfilePageView,
    EditProfilePageView,
    CreateProfilePageView
  
)



app_name = "members"
urlpatterns = [
   path('register/',user_register,name='register'),
   path('login/',user_login,name='login'),
   path('logout/',user_logout, name="logout"),
   path('edit_profile/',UserEditView.as_view(), name="edit_profile"),
   path('password/',PasswordChangeView.as_view(template_name=  'members/change_password.html'),name ='password'),
   path('<int:pk>/profile',ShowProfilePageView.as_view(),name = 'show_profile'),
   path('<int:pk>/edit_profile_page',EditProfilePageView.as_view(),name='edit_profile_page'),
   path('create_profile_page/',CreateProfilePageView.as_view(),name = 'create_profile_page'),
  
]

posts/urls.py
from unicodedata import name
from django.urls import path

from posts.models import Category
from .views import (
   DeletePostView,
   HomeView,
   DetailsVeiw,
   AddPostView,
   UpdatePostView,
   DeletePostView,
   AddCategoryView,
   categoryview,
   # likeView,
   AddCommentView
   
)


app_name = "posts"
urlpatterns = [
   path('',HomeView.as_view(), name='home'),
   path('details/<int:pk>',DetailsVeiw.as_view(), name = 'details'),
   path('add_post/',AddPostView.as_view(),name="add_post"),
   path('add_category/',AddCategoryView.as_view(),name="add_category"),
   path('edit/<int:pk>',UpdatePostView.as_view(), name='edit_post'),
   path('delete/<int:pk>',DeletePostView.as_view(), name='delete_post'),
   path('category/<str:category>',categoryview,name="category"),
   # path('like_post/<int:pk>',likeView,name="like_post"),
   path('details/<int:pk>/add_comment',AddCommentView.as_view(),name="add_comment"),
   
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
      {% include 'header.html' %}
      {% block content %}{% endblock content %}
      {% include 'footer.html' %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
  </body>
</html>

templates/footer.html
<footer class="page-footer text-center bg-dark" >
    <div class="container my-5">
      <div class="w3-center w3-small w3-opacity center-align">
        <br><br>
        Easy Learning is optimized for learning and training. Examples might be simplified to improve reading and learning.
        Tutorials, references, and examples are constantly reviewed to avoid errors, but we cannot warrant full correctness of all content.
        While using Easy Learning, you agree to have read and accepted our <a href="">terms of use</a>, 
        <a href="">cookie and privacy policy</a>.<br><br>
        <a href="">Copyright 2022</a> by references Data. All Rights Reserved.<br>
        <!-- <a href="">W3Schools is Powered by W3.CSS</a>.<br><br> -->
        <p class="small text-muted text-center my-5">
            
          <a href="{{post.author.profile.website_url}}">Website</a> |
         
         
          <a href="{{post.author.profile.facebook_url}}">Facebook</a> |
          
          
          <a href="{{post.author.profile.twitter_url}}">Twitter</a> |
          
         
          <a href="{{post.author.profile.instagram_url}}">Instagram</a> |
         
         
          <a href="{{post.author.profile.linkedin_url}}">LinkedIn</a>
       
        </p>
        <br><br>
        <br>
        </div>
    </div>
  </footer>

templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg text-light bg-dark">
  <a class="navbar-brand" href="{% url 'posts:home' %}"><strong>Easy Learning</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:home' %}">Home <span class="sr-only">({{request.user}})</span></a>
      </li>
 
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-expanded="false">
        Categories
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% for item in category_menu %}
        <a class="dropdown-item" href="{% url 'posts:category' item|slugify %}">{{item}}</a>
        {% endfor %}
         
      </div>
    </li>

      {% if user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:add_post' %}">Add Post</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:add_category' %}">Add Category</a>
      </li>
    
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'members:password' %}">Change Password</a>
      </li>
 
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'members:register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'members:login' %}">Login</a>
      </li>
     
      
      {% endif %}
     
    </ul>
    {% if user.is_authenticated %}
    
    <ul class="navbar-nav ml-auto" >
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-expanded="false">
        {{user.first_name}} {{user.last_name}}
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'members:edit_profile' %}">Edit Settings</a>
        {% if user.profile.id %}
        <a class="dropdown-item" href="{% url 'members:edit_profile_page' user.profile.id%}">Edit Profile Page</a>
        <a class="dropdown-item" href="{% url 'members:show_profile' user.profile.id %}">Show Profile Page</a>
        {% else %}
        <a class="dropdown-item" href="{% url 'members:create_profile_page' %}">Create Profile</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'members:logout' %}">Logout</a>
      </div>
    </li>
    
    </ul>
  
    {% endif %}
  </div>

</nav>